apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      labels:
        env: demo
        type: frontend
        app: nginx
    spec:
      containers:
      - name: nginx-containers
        image: nginx
        ports:
        - containerPort: 80 